name: 🐛 Bug Report
description: Report a bug in a template
title: "🐛 [BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us fix it.

  - type: dropdown
    id: template
    attributes:
      label: Which template is affected?
      description: Select the template where you found the bug
      options:
        - noir-vite
        - cairo-vite (future)
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'cza new [template] myproject'
        2. Navigate to project directory
        3. Run '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The project should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the project...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Any error messages or relevant logs
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - cza version: [run `cza --version`]
        - Node version: [run `node --version`]
        - Rust version: [run `rustc --version`]
        - Other relevant tools:
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have tested with the latest version of cza
          required: true