name: 💡 Feature Request
description: Suggest an improvement to an existing template
title: "💡 [Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea in detail.

  - type: dropdown
    id: template
    attributes:
      label: Which template does this relate to?
      description: Select the template this feature request is for
      options:
        - noir-vite
        - cairo-vite (future)
        - All templates
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, when developing with this template...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: The template should include...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Another approach could be...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of this feature in other projects or templates
      placeholder: |
        - Project X implements this by...
        - Template Y has a similar feature...

  - type: checkboxes
    id: impact
    attributes:
      label: Feature Impact
      description: What areas would this feature affect?
      options:
        - label: Development experience
          required: false
        - label: Build/compilation process
          required: false
        - label: Testing capabilities
          required: false
        - label: Documentation
          required: false
        - label: Performance
          required: false
        - label: Developer tooling
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to implement this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request